### ISSUE TITLE
[webapp/backend] Cookie is not being overwritten properly

### ISSUE THREAD

**Issue by qrn99** [jangarong/chalkling#10]
Debug with Localhost:
login as user2, refresh the page, login as user1, then gives back user2 friendliest.

**Comment by jangarong** [comment]
The reason why is because the client never requests to log off in the first place. 

This issue will be fixed with #9, so I'll write down what I need to fix both issues at once.

**Comment by jangarong** [comment]
See new commits:
https://github.com/jangarong/chalkling/commit/7d992477951d5c9f55a85e1d741508e7955c9622
https://github.com/jangarong/chalkling/commit/f02d504084469edbdbbd331f627464a8e9b19f86
